### ISSUE TITLE
[Python 3] New API change to the use of color_cycler

### ISSUE THREAD

**Issue by piyueh** [mesnardo/scripts#2]
In Python 3, it seems matplotlib has removed the old usage of `color_cycler` like what is at [line 118](https://github.com/mesnardo/scripts/blob/master/scripts/PetIBM/logSummaryReader.py#L118) in **logSummaryReader.py**.

According to the suggested [*new API usage*](http://matplotlib.org/api/api_changes.html#color-cycle-deprecated),  [line 118](https://github.com/mesnardo/scripts/blob/master/scripts/PetIBM/logSummaryReader.py#L118) in **logSummaryReader.py** should be modified to

```
color_cycle = ax._get_lines.prop_cycler
```

And [line 126](https://github.com/mesnardo/scripts/blob/master/scripts/PetIBM/logSummaryReader.py#L126) in the same file should be modified correspondingly  to:

```
... color=next(color_cycle)['color'], ...
```

Also, [line 20](https://github.com/mesnardo/scripts/blob/master/styles/mesnardo.mplstyle#L20) in **mesnardo.mplstyle** is deprecated in Python 3, though it has not been deleted yet. The new usage is:
```
axes.prop_cycle : cycler('color', 
    ['348ABD', '7A68A6', 'A60628', '467821', 'CF4457', '188487', 'E24A33'])
```

**Comment by mesnardo** [comment]
`color_cycle` is deprecated in the new version of matplotlib available in the Anaconda distribution (both Python 2 and 3).

I update the different files.

Thank you @piyueh
